services:
  p40la-ihost:
    build: .
    image: paulomcnally/p40la-ihost:latest
    container_name: p40la-ihost
    restart: unless-stopped
    ports:
      - "8088:8088"
    volumes:
      - p40la-ihost-data:/app/data
    environment:
      - PORT=8088
      - DATA_DIR=/app/data
      - LOG_LEVEL=info
      - VERSION=0.4.15

volumes:
  p40la-ihost-data:
