ALTER TABLE autos ADD COLUMN motor TEXT NOT NULL DEFAULT '';
ALTER TABLE autos ADD COLUMN chasis TEXT NOT NULL DEFAULT '';
ALTER TABLE autos ADD COLUMN vin TEXT NOT NULL DEFAULT '';
ALTER TABLE autos ADD COLUMN placa TEXT NOT NULL DEFAULT '';

ALTER TABLE auto_services ADD COLUMN policy_number TEXT NOT NULL DEFAULT '';
ALTER TABLE auto_services ADD COLUMN certificate TEXT;
ALTER TABLE auto_services ADD COLUMN insurer_number TEXT NOT NULL DEFAULT '';
